2025-08-24 11:23:01.583263: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-08-24 11:23:03.491 | INFO     | __main__:fuzz_single:290 - Start fuzzing CollectiveInitializeCommunicator with info (group_key, rank, group_size, communication_hint='auto', timeout_seconds=0, name=None)
2025-08-24 11:23:03.491 | INFO     | __main__:fuzz_single:308 - [Round 1] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([1, 8, 4, 8, 4, 4, 4, 1], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=15.220234212171135,)
2025-08-24 11:23:03.591 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_key, got [1,8,4,8,4,4,4,1] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.592 | INFO     | __main__:fuzz_single:308 - [Round 2] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([8, 2, 4, 1], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([1, 4], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=14.703207595063473,)
2025-08-24 11:23:03.593 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [1,4] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.593 | INFO     | __main__:fuzz_single:308 - [Round 3] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([1], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([0], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([8], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=11.815085518302766,)
2025-08-24 11:23:03.595 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [8] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.595 | INFO     | __main__:fuzz_single:308 - [Round 4] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([0, 0], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([2, 8, 2, 0, 0, 0, 4, 2], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([4, 4], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=8.465124159528973,)
2025-08-24 11:23:03.596 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [4,4] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.596 | INFO     | __main__:fuzz_single:308 - [Round 5] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([8], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([2, 8, 1, 0], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=11.418747707888691,)
2025-08-24 11:23:03.597 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_key, got [8] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.598 | INFO     | __main__:fuzz_single:308 - [Round 6] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([1], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([1, 1, 8, 4], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=4.784205011950463,)
2025-08-24 11:23:03.599 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_key, got [1] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.599 | INFO     | __main__:fuzz_single:308 - [Round 7] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([2, 1, 2, 1], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([1, 4, 8, 8, 0, 1, 8, 0], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([2, 4, 2, 8], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=4.988385077056469,)
2025-08-24 11:23:03.600 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [2,4,2,8] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.600 | INFO     | __main__:fuzz_single:308 - [Round 8] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([8, 1, 8, 0], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([0, 0, 1, 2, 2, 2, 2, 1], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([2], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=9.873286268566762,)
2025-08-24 11:23:03.602 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [2] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.602 | INFO     | __main__:fuzz_single:308 - [Round 9] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([8, 4, 1, 8, 1, 1, 0, 1], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([0, 1], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=0.6812671122534044,)
2025-08-24 11:23:03.603 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_key, got [8,4,1,8,1,1,0,1] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.603 | INFO     | __main__:fuzz_single:308 - [Round 10] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([8, 0, 8, 1, 8, 4, 4, 8], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([2, 0, 0, 4], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([8, 0, 2, 1, 0, 4, 2, 2], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=11.475844110280148,)
2025-08-24 11:23:03.604 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [8,0,2,1,0,4,2,2] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.604 | INFO     | __main__:fuzz_single:308 - [Round 11] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([8], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([1, 0, 4, 8, 2, 4, 4, 8], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([2], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=14.4260307706623,)
2025-08-24 11:23:03.606 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [2] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.606 | INFO     | __main__:fuzz_single:308 - [Round 12] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=7.211419561183952,)
2025-08-24 11:23:03.607 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} User Provided rank is invalid. It should be between [0, group_size) [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.607 | INFO     | __main__:fuzz_single:308 - [Round 13] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([4, 4, 4, 0], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([1, 1], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=9.835663894636776,)
2025-08-24 11:23:03.609 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [1,1] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.609 | INFO     | __main__:fuzz_single:308 - [Round 14] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([4], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([4, 0], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([8], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=4.052500798571533,)
2025-08-24 11:23:03.610 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [8] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.610 | INFO     | __main__:fuzz_single:308 - [Round 15] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([4, 4, 8, 4, 4, 4, 2, 8], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([0, 4], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([2, 4, 8, 1, 0, 8, 1, 8], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=7.40407138942165,)
2025-08-24 11:23:03.612 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [2,4,8,1,0,8,1,8] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.612 | INFO     | __main__:fuzz_single:308 - [Round 16] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([0, 8], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([4, 0], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([0, 1, 1, 4], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=6.4236343311860455,)
2025-08-24 11:23:03.613 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [0,1,1,4] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.614 | INFO     | __main__:fuzz_single:308 - [Round 17] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([2, 0], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=14.051864169376048,)
2025-08-24 11:23:03.615 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_key, got [2,0] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.615 | INFO     | __main__:fuzz_single:308 - [Round 18] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([4, 2], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([4, 4, 2, 0], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=7.265808284505899,)
2025-08-24 11:23:03.616 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [4,4,2,0] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.616 | INFO     | __main__:fuzz_single:308 - [Round 19] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([8], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([2, 0], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([0, 1, 1, 2, 0, 4, 4, 2], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=12.267608798067752,)
2025-08-24 11:23:03.617 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [0,1,1,2,0,4,4,2] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.618 | INFO     | __main__:fuzz_single:308 - [Round 20] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([8, 0], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([2], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=0.6987949630738256,)
2025-08-24 11:23:03.619 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [2] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.619 | INFO     | __main__:fuzz_single:308 - [Round 21] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([4], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([0, 4, 2, 8, 4, 8, 4, 2], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=15.135133183878851,)
2025-08-24 11:23:03.620 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [0,4,2,8,4,8,4,2] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.620 | INFO     | __main__:fuzz_single:308 - [Round 22] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([1, 0], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=12.641887488892067,)
2025-08-24 11:23:03.622 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [1,0] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.622 | INFO     | __main__:fuzz_single:308 - [Round 23] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([1], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([8, 0], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=11.846801747099338,)
2025-08-24 11:23:03.623 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [8,0] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.623 | INFO     | __main__:fuzz_single:308 - [Round 24] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([8, 0, 4, 0, 8, 2, 0, 4], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([2], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=13.815425375422638,)
2025-08-24 11:23:03.624 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [2] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.624 | INFO     | __main__:fuzz_single:308 - [Round 25] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([4], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([2], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=11.719987887436899,)
2025-08-24 11:23:03.626 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [2] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.626 | INFO     | __main__:fuzz_single:308 - [Round 26] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([2, 8, 8, 2, 1, 1, 4, 8], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([2, 0, 4, 2, 4, 2, 2, 0], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=5.310421638085737,)
2025-08-24 11:23:03.627 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [2,0,4,2,4,2,2,0] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.627 | INFO     | __main__:fuzz_single:308 - [Round 27] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([4], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([4, 8, 0, 8, 1, 2, 2, 2], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=2.218282132739058,)
2025-08-24 11:23:03.629 | WARNING  | __main__:fuzz_single:321 - EROOR: {{function_node __wrapped__CollectiveInitializeCommunicator_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unexpected dimensions on input group_size. It shoulbe a scalar, got tensor with shape [4,8,0,8,1,2,2,2] [Op:CollectiveInitializeCommunicator]
2025-08-24 11:23:03.629 | INFO     | __main__:fuzz_single:308 - [Round 28] Generated code: 
tf.raw_ops.CollectiveInitializeCommunicator(group_key=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),rank=tf.random.uniform([2], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),group_size=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000),communication_hint="b'auto'",timeout_seconds=5.5835987165178365,)
